### ISSUE TITLE
_config_local.yml 内 social ボタンの URL を後に更新する

### ISSUE THREAD

**Issue by dadaa** [chirimen-oh/chirimen-oh.github.io#13]
現状：
social:
- title: "facebook"
  url: "https://www.facebook.com/groups/mozopenhard/"
- title: "twitter"
  url: "https://twitter.com/chirimen_oh"
- title: "github"
  url: "https://github.com/chirimen-org"

github と facebook の URL はあとで変更が必要になりそうですので，忘れないように issue としてあげておきます．

**Comment by gurezo** [comment]
2016/04/30 CHIRIMEN Open Hardware release後：
social:
- title: "facebook"
  url: "https://www.facebook.com/groups/chirimen/"
- title: "github"
  url: "https://github.com/chirimen-oh"

merge されたら、close
