### ISSUE TITLE
コミュニティ参加を促すページ構成の改善

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-oh.github.io#29]
join us　のようなわかりやすいリンクなどを設置し、
-facebook : user community
-github : contributer community
（おおよその今の使われ方）
等への参加を促すページ構成の改善を考えたいです。

**Comment by gurezo** [comment]
その件に関しては、下記issueの関連しているので追記します。
[ slack 参加フォームを作る #19 ](https://is.gd/5aD5TE)

**Comment by gurezo** [comment]
#41 , [ slack 参加フォームを作る #19 ](https://is.gd/5aD5TE)
上記対応が取れたので、close
