### ISSUE TITLE
スルーホール(CN1/2)の情報

### ISSUE THREAD

**Issue by ghost** [chirimen-oh/chirimen-oh.github.io#37]
https://chirimen.org/docs/ja/board_connectors.html

あたりに以下の情報があるとよさそうです。
- 2.54mmピッチである
- お勧めのヘッダ・スルーホール用ワイヤ

**Comment by ghost** [comment]
https://github.com/chirimen-oh/Support-And-FAQ/issues/2
- 電圧
- 何mA流せるか

https://github.com/chirimen-oh/Support-And-FAQ/issues/3
- 初期状態
- pull up or down

も必要そうです。

**Comment by naokisekiguchi** [comment]
スルーホールの情報を追記してみました。
https://github.com/chirimen-oh/chirimen-oh.github.io/pull/50

このあたりそんなに詳しくないので、情報が間違っていないかどなたかにご確認いただきたいです。

**Comment by MSakamaki** [comment]
以下のexcelを参考に今迄作っていたのですが、
https://github.com/chirimen-oh/CHIRIMEN-tools/blob/master/CHIRIMEN%20pin%20config.xlsx

CN1のpin2と3にもGPIOがあった気がします。(動作確認させた記憶があるのですが、うろ覚えですいません)

**Comment by naokisekiguchi** [comment]
CN1のpin2,3はI2Cの2pinがありますね。設定すればGPIOとして使うこともできますが、リリースイメージではI2Cとして機能しているということだと。

**Comment by MSakamaki** [comment]
なるほど、設定すればGPIOとして使用可能と言う話だったのですね。
