### ISSUE TITLE
CHIIRMENボード発売正式発表に伴う修正

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/chirimen-oh.github.io#62]
## Expected Behavior

製品販売情報無
## Actual Behavior

FAQ修正, NEWSページ追記
## Steps to Reproduce the Issue
1. FAQ修正
2. NEWSページ追記
   3.
## Specifications

(The version of the project, browser etc.)

**Comment by gurezo** [comment]
修正箇所が見つかった為、Reopen

**Comment by kohichi000000** [comment]
ありがとうございます。

ご提案ですが、値段に関する項目は削除するか、残すにしても値段そのものは削除して「詳しくは販売店のページをご覧ください」( Please see each resellers' site for details. ) 程度がいいと思いますがいかがでしょうか？
＜理由＞
・コミュニティが値付けした標準価格であれば書いてもいいですが、そうではないため。
・値段はresellerによって（もちろん時期によっても）異なってくる可能性が高く、書いてしまうと上げ下げしづらくなると思われるため。
＜参考＞
・Raspberry piは本家ページのFAQに書いている（おそらくRaspberry財団が決めたものであると思われる。）
・Arduinoは本家ページに書いていない。

**Comment by gurezo** [comment]
了解しました。
上記を踏まえた上で、修正してみます。
