### ISSUE TITLE
周辺デバイスページに any-issues #158 を反映

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/chirimen-oh.github.io#66]
https://github.com/chirimen-oh/any-issues/issues/158

**Comment by tadfmac** [comment]
https://chirimen.org/docs/ja/peripherals.html への反映を考えていたのですが、日本語版を[先に作ってみた](https://github.com/tadfmac/chirimen-oh.github.io/blob/issues/%2366/docs/ja/peripherals.md)ところ、こうした反映を行うより、wiki化した方が良いのでは？とも思いましたので、wiki版案を作成しました。

https://github.com/tadfmac/chirimen-oh.github.io/wiki/peripherals(ja)
https://github.com/tadfmac/chirimen-oh.github.io/wiki/peripherals(en)

ご意見をお願いします。
(wikiで良いならクイックスタートから直接リンクを貼ればよいかと)

尚、上記リストが #158 の反映ということもあって、I2CやGPIOに接続するものの情報は含まれておりませんが、こちらも別途Wikiで「接続確認パーツリスト」のようなものを立ててしまいたいと考えています。#159 の反映時に実施したい考えです。

**Comment by gurezo** [comment]
ハードのリンク先が日本語のみが気になるところです。
・・・が、海外の方もリンク先から発注出来るので大丈夫かと思います。

**Comment by tadfmac** [comment]
@gurezo さんありがとうございます。
今は仮にfork先のwikiに書いていますが、皆さんwikiで問題ないようでしたら、このリポジトリのwikiに移したいと思います。(コピペで行けますし)
もし、気になるところがあったら修正いただけたら助かります！

**Comment by tadfmac** [comment]
https://github.com/chirimen-oh/chirimen-oh.github.io/pull/69

**Comment by gurezo** [comment]
マージしたので、close
