### ISSUE TITLE
MDN<https://developer.mozilla.org/ja/Firefox_OS/Board_guide/CHIRIMEN>からリソースを移設する。

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-oh.github.io#8]

**Comment by satakagi** [comment]
クイックスタートガイド
日 http://chirimen-org.github.io/docs/ja/quickStart.html
英 http://chirimen-org.github.io/docs/ja/quickStart.html

Q&A
日 http://chirimen-org.github.io/docs/ja/QA.html
のプルリクを行いました。 #7

**Comment by satakagi** [comment]
#7

**Comment by satakagi** [comment]
あ、あと、スペックシートも作ってクイックスタートガイドのところからリンク張ってあります。

**Comment by MSakamaki** [comment]
Mixed Content のエラーでcss参照が・・・
https://chirimen-org.github.io/docs/ja/FAQ.html

そういえばgithub pagesは混在コンテンツ許容しない仕様でしたっけ・・・

CSSは後で整えましょう

<img width="977" alt="2016-04-28 14 39 56" src="https://cloud.githubusercontent.com/assets/2183053/14876367/20206264-0d4f-11e6-84a6-9375c3696fa1.png">

**Comment by satakagi** [comment]
CSSはノーアイデアだったのでよく私が使っているW3Cドキュメント用の一番ベーシックなものを引っ張っていました。　もう少しホームページと合ったCSSがあればそちらに、

**Comment by MSakamaki** [comment]
@satakagi 
了解です。
とりあえずメニューとか含め全滅するので「動かす為に」w3cドキュメント用のcssを使わせてもらいます。
別issuesとかでデザインをし直そうとおもいます。
