### ISSUE TITLE
chirimen.org ホームページ　@ github pagesの端末上での動作確認方法（環境設定法）を各OS用で明らかにする

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/chirimen-oh.github.io#9]

**Comment by satakagi** [comment]
# Windows

## prepare env.
- http://jekyll-windows.juthilo.com/
  - Note: you should install ruby 2.2.4 (2.3.0 is incompatible...)
  - gem install jekyll
  - gem install rouge
  - gem install wdm
- gem install katana
- gem install jemoji
- gem install jekyll-paginate
- gem install github-pages
- gem install compass
- gem install sass

## clone repo.

## mod _config.yml

<pre>
< #url: "https://chirimen-org.github.io"
---
> url: "https://chirimen-org.github.io"
15c15
< #baseurl: .
---
> baseurl: .
19c19
< #google-tracking-id: "UA-75123287-2"
---
> google-tracking-id: "UA-75123287-2"
25c25
< #force-https: True
---
> force-https: True
77,82c77,82
< #icon-36p: "/img/web/android-icon-36x36.png"
< #icon-48p: "/img/web/android-icon-48x48.png"
< #icon-72p: "/img/web/android-icon-72x72.png"
< #icon-96p: "/img/web/android-icon-96x96.png"
< #icon-144p: "/img/web/android-icon-144x144.png"
< #icon-192p: "/img/web/android-icon-192x192.png"
---
> icon-36p: "/img/web/android-icon-36x36.png"
> icon-48p: "/img/web/android-icon-48x48.png"
> icon-72p: "/img/web/android-icon-72x72.png"
> icon-96p: "/img/web/android-icon-96x96.png"
> icon-144p: "/img/web/android-icon-144x144.png"
> icon-192p: "/img/web/android-icon-192x192.png"
</pre>

**Comment by satakagi** [comment]
こんな感じで大丈夫ですか？　一応　それらしく動いてる感はありますが・・

**Comment by MSakamaki** [comment]
どなかた後１名くらいwindows環境で動作確認がとれれば、自分の方でREADMEに色々書いてこのissuesはcloseしたいと思います。

**Comment by kohichi000000** [comment]
私windows 10ですが上記でできることを確認しました。
